---
author:
  - 'Mike Eldridge <diz@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.89'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Hopkins-Plugin-HMI
no_index:
  directory:
    - inc
    - share
requires:
  Catalyst::Action::RenderView: 0.08
  Catalyst::Engine::Embeddable: 0.000002
  Catalyst::Plugin::Authentication: 0.100092
  Catalyst::Plugin::Session: 0.24
  Catalyst::Plugin::Session::Store::FastMmap: 0.11
  Class::Accessor::Fast: 0.31
  File::ShareDir: 1.00
  Hopkins: 0.900
  POE::Component::Server::HTTP: 0.09
  Sys::Hostname::FQDN: 0.10
resources:
  license: http://dev.perl.org/licenses/
version: 0.900_01
